### ISSUE TITLE
ERROR Cannot load adapter skype - TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by bwiggs** [netpro2k/hubot-skype#13]
Trying to install this on a mac mini at work. Getting problems trying to run with skype adapter.

```
$ ./bin/hubot -a skype
[Tue Jan 29 2013 10:27:45 GMT-0700 (MST)] ERROR Cannot load adapter skype - TypeError: Cannot read property 'prototype' of undefined
TypeError: Cannot call method 'on' of null
    at Object.<anonymous> (/Users/hubot/sc-hubot/node_modules/hubot/bin/hubot:105:19)
    at Object.<anonymous> (/Users/hubot/sc-hubot/node_modules/hubot/bin/hubot:109:4)
    at Module._compile (module.js:449:26)
    at Object.exports.run (/Users/hubot/sc-hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:79:25)
    at compileScript (/Users/hubot/sc-hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/command.js:177:29)
    at fs.stat.notSources.(anonymous function) (/Users/hubot/sc-hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/command.js:152:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

```
$ node --version
v0.8.18
$ npm --version
1.2.2
$ npm list
hosted-hubot@2.2.0 /Users/hubot/sc-hubot
├─┬ hubot@2.2.0
│ ├── coffee-script@1.3.1
│ ├─┬ connect@2.1.0
│ │ ├── crc@0.1.0
│ │ ├── debug@0.7.0
│ │ ├── formidable@1.0.9
│ │ ├── mime@1.2.4
│ │ └── qs@0.4.2
│ ├── connect_router@1.8.6
│ ├── log@1.3.0
│ └── scoped-http-client@0.9.7
├─┬ hubot-scripts@2.4.1
│ ├─┬ hubot@2.4.6
│ │ ├── coffee-script@1.4.0
│ │ ├─┬ connect@2.3.4
│ │ │ ├── bytes@0.0.1
│ │ │ ├── cookie@0.0.4
│ │ │ ├── crc@0.2.0
│ │ │ ├── debug@0.7.0
│ │ │ ├── formidable@1.0.11
│ │ │ ├── fresh@0.0.1
│ │ │ ├── mime@1.2.4
│ │ │ ├── qs@0.4.2
│ │ │ └── range-parser@0.0.4
│ │ ├── connect_router@1.8.6
│ │ ├── log@1.3.0
│ │ └── scoped-http-client@0.9.7
│ └─┬ redis@0.7.2
│   └── hiredis@0.1.14
├── hubot-skype@0.0.2
└── optparse@1.0.3
```

**Comment by bwiggs** [comment]
Another silly mistake. The download link on http://hubot.github.com links to hubot v2.2.0. Had to get the latest from the repo, and everything works.
