### ISSUE TITLE
ERROR Cannot load adapter skype - TypeError: Object #<Object> has no method 'robot'

### ISSUE THREAD

**Issue by ghost** [netpro2k/hubot-skype#4]
Hello,

There is a strange error on CentOS 6.3 with Ruby 1.9.3 with the latest patchset -> on bin/hubot -a skype I get the following error trace:

ERROR Cannot load adapter skype - TypeError: Object #<Object> has no method 'robot'
TypeError: Object #<Object> has no method 'robot'
    at Object.<anonymous> (/opt/hubot/node_modules/hubot-skype/src/skype.coffee:9:28)
    at Object.<anonymous> (/opt/hubot/node_modules/hubot-skype/src/skype.coffee:94:4)
    at Module._compile (module.js:446:26)
    at Object..coffee (/usr/lib/nodejs/coffee-script/lib/coffee-script/coffee-script.js:22:21)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Robot.loadAdapter (/opt/hubot/src/robot.coffee:215:31)
    at new Robot (/opt/hubot/src/robot.coffee:47:14)
TypeError: Cannot call method 'on' of null
    at Object.<anonymous> (/opt/hubot/bin/hubot:105:19)
    at Object.<anonymous> (/opt/hubot/bin/hubot:109:4)
    at Module._compile (module.js:446:26)
    at Object.run (/usr/lib/nodejs/coffee-script/lib/coffee-script/coffee-script.js:79:25)
    at /usr/lib/nodejs/coffee-script/lib/coffee-script/command.js:175:29
    at /usr/lib/nodejs/coffee-script/lib/coffee-script/command.js:150:18
    at [object Object].<anonymous> (fs.js:123:5)
    at [object Object].emit (events.js:64:17)
    at Object.oncomplete (fs.js:1188:12)

And ideas?

**Comment by digitalpbk** [comment]
Similar error on windows 
hubot version: 2.3.2
node: 0.8.2

D:\Hubot\node_modules\hubot>node .\node_modules\coffee-script\bin\coffee .\bin\h
ubot -a skype
[Sat Aug 04 2012 12:32:52 GMT+0530 (India Standard Time)] ERROR Cannot load adap
ter skype - TypeError: Object #<Object> has no method 'robot'
TypeError: Object #<Object> has no method 'robot'
    at Object.<anonymous> (D:\Hubot\node_modules\hubot\node_modules\hubot-skype\
src\skype.coffee:9:28)
    at Object.<anonymous> (D:\Hubot\node_modules\hubot\node_modules\hubot-skype\
src\skype.coffee:94:4)
    at Module._compile (module.js:449:26)
    at Object.require.extensions..coffee (D:\Hubot\node_modules\hubot\node_modul
es\coffee-script\lib\coffee-script\coffee-script.js:22:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Robot.loadAdapter (D:\Hubot\node_modules\hubot\src\robot.coffee:215:31)
    at new Robot (D:\Hubot\node_modules\hubot\src\robot.coffee:47:14)
TypeError: Cannot call method 'on' of null
    at Object.<anonymous> (D:\Hubot\node_modules\hubot\bin\hubot:105:19)
    at Object.<anonymous> (D:\Hubot\node_modules\hubot\bin\hubot:109:4)
    at Module._compile (module.js:449:26)
    at Object.exports.run (D:\Hubot\node_modules\hubot\node_modules\coffee-scrip
t\lib\coffee-script\coffee-script.js:79:25)
    at compileScript (D:\Hubot\node_modules\hubot\node_modules\coffee-script\lib
\coffee-script\command.js:175:29)
    at fs.stat.notSources.(anonymous function) (D:\Hubot\node_modules\hubot\node
_modules\coffee-script\lib\coffee-script\command.js:150:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)

**Comment by netpro2k** [comment]
Have only gotten this running on MacOS so far (and with much difficulty). Cant really provide any help for windows or linux, but if you do figure it out, please send instructions and I can add to readme.

**Comment by digitalpbk** [comment]
hubot-skype is not compatible with the latest hubot, nothing to do with the os.

**Comment by netpro2k** [comment]
ah, maybe adapter format has changed or something. WIll look into it when I get a chance.

**Comment by netpro2k** [comment]
I have now updated this to work with the latest version of hubot, published to npm, added better error reporting, as well as notes on OS specific issues in the readme.

Let me know if you are still having issues with the latest version.
