### ISSUE TITLE
does not work in ubuntu 12 LTS

### ISSUE THREAD

**Issue by swood** [netpro2k/hubot-skype#6]
After simple installing hubot and manual installing hubot-skype. I can't run hubot by command:
<code>
./bin/hubot -a skype
</code>

After running I see next errors:
<code>
 ./bin/hubot -a skype
[Thu Aug 02 2012 00:45:01 GMT+0400 (MSK)] ERROR Cannot load adapter skype - Error: Cannot find module 'hubot'
Error: Cannot find module 'hubot'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/opt/hubot/node_modules/hubot-skype/src/skype.coffee:9:11)
    at Object.<anonymous> (/opt/hubot/node_modules/hubot-skype/src/skype.coffee:94:4)
    at Module._compile (module.js:444:26)
    at Object..coffee (/usr/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:22:21)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
TypeError: Cannot call method 'on' of null
    at Object.<anonymous> (/opt/hubot/bin/hubot:105:19)
    at Object.<anonymous> (/opt/hubot/bin/hubot:109:4)
    at Module._compile (module.js:444:26)
    at Object.run (/usr/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:79:25)
    at /usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:175:29
    at /usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:150:18
    at [object Object].<anonymous> (fs.js:115:5)
    at [object Object].emit (events.js:64:17)
    at afterRead (fs.js:1111:12)
    at Object.wrapper [as oncomplete](fs.js:254:17)
</code>

What I to do is not right?

**Comment by netpro2k** [comment]
I have now updated this to work with the latest version of hubot, published to npm, added better error reporting, as well as notes on OS specific issues in the readme.

Let me know if you are still having issues with the latest version.
